---

- name: install dependencies
  include_tasks: packages-{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}.yml

- name: Get php version
  command: /usr/bin/php --version
  register: php5cli_current
  ignore_errors: yes

- import_tasks: php-cli.yml
  when: php5cli_current | failed or not php5cli_current.stdout | search(php5cli_version_string_match)

- import_tasks: config.yml

- import_tasks: ext-apcu.yml

- import_tasks: ext-imagick.yml

- import_tasks: ext-igbinary.yml

- import_tasks: ext-memcached.yml

- import_tasks: ext-redis.yml
