---

- name: install dependencies
  include_tasks: packages-{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}.yml

- name: Get php version
  command: php --version
  register: php5cli_current
  ignore_errors: yes

- set_fact: php5cli_real_version="{{ php5cli_version | regex_replace('-\\d+$', '') }}"

- name: Install php-cli
  import_tasks: php-cli.yml
  when: php5cli_current.rc != 0 or php5cli_current.stdout.find("PHP {{ php5cli_real_version }} (cli)") == -1

- import_tasks: config.yml

- import_tasks: ext-apcu.yml

- import_tasks: ext-imagick.yml

- import_tasks: ext-igbinary.yml

- import_tasks: ext-memcached.yml

- import_tasks: ext-redis.yml
